// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Creacion de cuenta', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Creacion de cuenta', async function() {
    await driver.get("http://localhost:3000/newAccount")
    await driver.manage().window().setRect({ width: 1440, height: 875 })
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("juan ")
    await driver.findElement(By.id("lastname")).sendKeys("arango")
    await driver.findElement(By.id("email")).sendKeys("juanmaracho10@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("Carolina2022")
    await driver.findElement(By.id("confirmPassword")).sendKeys("Carolina2022")
    await driver.findElement(By.css(".NewAccountForm_submit_btn__-P8Ic")).click()
    await driver.findElement(By.css(".NewAccountForm_submit_btn__-P8Ic")).click()
    await driver.close()
  })
})
