// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Inicio de sesion', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Inicio de sesion', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1440, height: 875 })
    await driver.findElement(By.css("a:nth-child(3) > button")).click()
    {
      const element = await driver.findElement(By.css("button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("juanmaracho10@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("Carolina19")
    await driver.findElement(By.css(".LoginForm_submit_btn__BeNeU")).click()
    await driver.close()
  })
})
